apiVersion: v1
kind: Pod

metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: AWS
    - name: trainer
      value: "Sivakumar Reddy M"
    - name: duration
      value: "120HRS"
