apiVersion: v1 
kind: Pod
metadata:
  name: backend-clusterip
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1 
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  selector:     # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80   # service port
    targetPort: 80

